"""empty message

Revision ID: 57a0e5a60449
Revises: 
Create Date: 2021-09-06 12:43:35.082381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a0e5a60449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('writer', sa.String(length=20), nullable=True),
    sa.Column('w_date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['writer'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    op.drop_table('member')
    # ### end Alembic commands ###
