"""empty message

Revision ID: 85e23d883f26
Revises: 
Create Date: 2021-09-29 14:56:56.489872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e23d883f26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('writer', sa.String(length=20), nullable=False),
    sa.Column('w_date', sa.DateTime(), nullable=False),
    sa.Column('itsBroNm', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('nation_wide',
    sa.Column('rk', sa.Integer(), nullable=False),
    sa.Column('itsBroNm', sa.String(length=20), nullable=True),
    sa.Column('areaNm', sa.String(length=20), nullable=True),
    sa.Column('areaCode', sa.String(length=20), nullable=False),
    sa.Column('baseYm', sa.String(length=20), nullable=False),
    sa.Column('imgLink', sa.String(length=100), nullable=False),
    sa.Column('dtlAddrNm', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rk')
    )
    op.create_table('region',
    sa.Column('rk', sa.Integer(), nullable=False),
    sa.Column('itsBroNm', sa.String(length=20), nullable=True),
    sa.Column('areaNm', sa.String(length=20), nullable=True),
    sa.Column('areaCode', sa.String(length=20), nullable=False),
    sa.Column('baseYm', sa.String(length=20), nullable=False),
    sa.Column('imgLink', sa.String(length=500), nullable=True),
    sa.Column('dtlAddrNm', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('rk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region')
    op.drop_table('nation_wide')
    op.drop_table('board')
    # ### end Alembic commands ###
